version: "3"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64 # M1で必要。それ以外の場合は削除する。
    container_name: local-mysql
    hostname: local-mysql
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306

volumes:
  db-store:

