services:
  zero:
    image: dgraph/dgraph:v24.1.5
    container_name: ${SERVER_NAME}_zero
    volumes:
      - /tmp/data:/dgraph
    ports:
      - ${DGRAPH_PORT_GRPC}:5080
      - ${DGRAPH_PORT_ADMIN}:6080
    restart: on-failure
    command: dgraph zero --my=zero:${DGRAPH_PORT_GRPC}
  alpha:
    image: dgraph/dgraph:v24.1.5
    container_name: ${SERVER_NAME}_alpha
    volumes:
      - /tmp/data:/dgraph
    ports:
      - ${DGRAPH_PORT_PUBLIC}:8080
      - ${DGRAPH_PORT_GRPC_PUBLIC}:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:${DGRAPH_PORT_GRPC_PRIVATE} --zero=zero:${DGRAPH_PORT_GRPC}  --security "whitelist=${DGRAPH_ALPHA_WHITELIST}"
  ratel:
    image: dgraph/ratel:v25.0.3
    container_name: ${SERVER_NAME}_ratel
    ports:
      - ${DGRAPH_PORT_RETEL}:8000

