version: "3.8"
services:
  zero:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - /tmp/data:/dgraph
    ports:
      - ${DGRAPH_PORT_GRPC}:5080
      - ${DGRAPH_PORT_ADMIN}:6080
    restart: on-failure
    command: dgraph zero --my=zero:${DGRAPH_PORT_GRPC}
  alpha:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - /tmp/data:/dgraph
    ports:
      - ${DGRAPH_PORT_PUBLIC}:8080
      - ${DGRAPH_PORT_GRPC_PUBLIC}:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:${DGRAPH_PORT_GRPC_PRIVATE} --zero=zero:${DGRAPH_PORT_GRPC}  --security "whitelist=0.0.0.0/0"
  ratel:
    image: dgraph/ratel:${DGRAPH_RETEL_VERSION}
    ports:
      - ${DGRAPH_PORT_RETEL}:8000

